### ISSUE TITLE
Pack Rat Rover Wheel issues

### ISSUE THREAD

**Issue by kjnicoletti** [BobPalmer/ExplorationPack#90]
1) The texture is not loading - it needs to be renamed from "GameData\UmbraSpaceIndustries\ExpPack\PackRat\MiniWheel\model000.dds" to "roverwheel1.dds"

![texture](https://cloud.githubusercontent.com/assets/10604230/15088850/97c0782a-13be-11e6-9c5b-0c8c8eda2868.png)

2) The front wheels of an assembled pack rat are always under stress, and once off the launch pad sink into the ground. They don't steer correctly and apply friction to the pack rat causing it to veer and slow down. Tested on Mun also, same behavior.

![wheel-stress](https://cloud.githubusercontent.com/assets/10604230/15088861/adff4a62-13be-11e6-93be-997566984101.png)

Tested with KSP 1.1.2.1260, ExpPack 5.2.1, USI Tools 7.2.1, CRP 5.1.1, Firespitter 7.2.3, KSP-AVC 1.1.6.1 and HyperEdit 1.5
Steps to reproduce: build a pack rat and drive it off the launch pad on to the grasslands. Right click on wheel to see stress that is always present on front wheels of pack rat.

**Comment by tito13kfm** [comment]
After some testing this seems to be caused by the front section being attached to the rover.  Without the front section the rover operates as expected.  Have not done testing with other things mounted to this attachment node to see if it's a mass issue, or something else.

**Comment by rladue** [comment]
I had the same two problems and the fix for #1 worked perfectly. As for #2 with the wheels continually locking up, I noticed a couple things. Once the wheels locked, if I did a quicksave and quickload, the wheels would revert back to normal on the load, but could potentially get blocked again which would need a new save/load.

I then build a pack rat without the front fender/light part, and it drove perfectly; wheels never got blocked. So then I figured it had to be something with the wheels bottoming out with the fenders. I noticed that the front fenders are not lined up with the center of the wheels like the back wheels are. I then attached the wheels but rotated the wheels 10 degrees forward (two shift-W clicks); but the wheels still bottomed out and locked up.

The fix I then found for #2 seems to be to make the spring and damper strength 2 in stead of 1 in the VAB. 
![screenshot2](https://cloud.githubusercontent.com/assets/19434158/15367459/bd0c2c4e-1cee-11e6-800c-4ab8ca23a34b.png)

I had no problems with the pack rat after bumping those two settings up, so it just comes from the wheels bottoming out and hitting the fender. Maybe a longer term fix could be for the wheels to "ignore" the fender area or something? Not sure, since I'm not a modder, but that seems to be where the issue is arising.
